### ISSUE TITLE
Un-initialised timer spamming error log

### ISSUE THREAD

**Issue by wayne-love** [wayne-love/sn_esp32#59]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 366, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 162, in state
    raise ValueError(
ValueError: Entity text.myspa_sleep_timer_2_end provides state 156:00 which does not match expected pattern [0-2][0-9]:[0-9]{2}
2024-11-09 15:11:43.104 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ state_attr("climate.local_daikin","energy_today")/1000 }}) renders=2>

**Comment by lucasnz** [comment]
Isn't this just a duplicate of #35 ?

**Comment by lucasnz** [comment]
Thinking about this, we should we validate the value before sending it in mqtt? If it fails validation (incorrect format), then don't send it. The problem with this is, if we don't send it then, it will be harder to debug. I'm inclined to say if we fix #35 the problem will go away and then we close this. Thoughts?
